version: "3"

services:
    # Nginx Service
    webserver:
        image: registry.gitlab.com/kuroi-taiyo/docker-store/nginx:latest
        container_name: dk_psychic_robot_webserver
        restart: unless-stopped
        tty: true
        ports:
            - 80:80
            - 443:443
            - 8080:8080
        volumes:
            - ./:/var/www
            - ./.docker/nginx/conf.d/:/etc/nginx/conf.d/
        networks:
            - psychic_robot-network

    # PHP Service
    app:
        image: registry.gitlab.com/kuroi-taiyo/docker-store/php:latest
        container_name: dk_psychic_robot_app
        restart: unless-stopped
        tty: true
        links:
            - database
        volumes:
            - ./:/var/www
        networks:
            - psychic_robot-network

    # Cron Service
    ofelia-cron:
        image: registry.gitlab.com/kuroi-taiyo/docker-store/cron:latest
        container_name: dk_psychic_robot_cron
        volumes:
            - /var/run/docker.sock:/var/run/docker.sock
            - ./.docker/cron/timezone:/etc/timezone
            - ./.docker/cron/localtime:/etc/localtime
        networks:
            - psychic_robot-network

    # MySQL Service
    database:
        image: registry.gitlab.com/kuroi-taiyo/docker-store/mysql:latest
        container_name: dk_psychic_robot_database
        restart: unless-stopped
        tty: true
        ports:
            - 3306:3306
        env_file: .env
        volumes:
            - psychic_robot-database:/var/lib/mysql/
            - ./.docker/scripts/:/scripts/
            - ./.docker/tmp-data/:/tmp-data/
        networks:
            - psychic_robot-network

#Docker Networks
networks:
    psychic_robot-network:
        driver: bridge

#Volumes
volumes:
    psychic_robot-database:
        driver: local
    psychic_robot-redis:
        driver: local
